repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: export_requirements
        name: export requirements
        entry: make export_requirements
        language: system
        always_run: true
        pass_filenames: false